### PR TITLE
Remove obsolete niceScrolls to improve performance (BL-11070)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[package.json, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-0b-449BD-OCKNtUwo:-N-0b-449BD-OCKNtUwp:b-o1eg8z) ([raw file](https://github.com/bloombooks/bloom-player/blob/6c57e8a62641b9dbd37853aac9b9394783fa9327/package.json#L49)):*
> ```JSON
>         "build4br": "yarn build && yarn tobloomreader",
>         "build4bd": "yarn build && yarn tobloom",
>         "build4bd-dev": "yarn build-dev && yarn tobloom"
> ```

I would like to see all of these commands removed. Developers should instead use `yarn link` to connect packages that they maybe working on while using in another context.



_Code quote:_
```JSON
build4bd
```

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[package.json, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-0b-449BD-OCKNtUwo:-N-UXtVm0PuNeobEKMEj:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/6c57e8a62641b9dbd37853aac9b9394783fa9327/package.json#L49)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I would like to see all of these commands removed. Developers should instead use `yarn link` to connect packages that they maybe working on while using in another context.
</blockquote></details>

Done.
___
*[src/bloom-player-core.tsx, line 215 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-UXwte3UNnTwlW6X6s:-N-UXwte3UNnTwlW6X6t:b-ommn6) ([raw file](https://github.com/bloombooks/bloom-player/blob/ed820a64f15d4602ac2109c91c18d2893d23e1ee/src/bloom-player-core.tsx#L215)):*
> ```XML
> 
> const kSelectorForPotentialNiceScrollElements =
>     ".bloom-translationGroup:not(.bloom-imageDescription) .bloom-editable.bloom-visibility-code-on";
> ```

It isn't obvious since I extracted it to a constant, but I added the `:not(.bloom-imageDescription)`. Previously, we were adding niceScrolls to the hidden image description text boxes.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/bloom-player-core.tsx, line 1837 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-YzmrOA4UkZg0GsVhF:-N-YzmrP6kxn4DEn61sl:buu68bm) ([raw file](https://github.com/bloombooks/bloom-player/blob/ed820a64f15d4602ac2109c91c18d2893d23e1ee/src/bloom-player-core.tsx#L1837)):*
> ```XML
>                     groupNiceScroll.remove();
>                 }
>             });
> ```

My intuition is that code that manipulates the real DOM should be in a useEffect, even if it runs on every render. This case may require it to be inline so that it runs before (e.g.) the actual render removes a div that contains one. If so, I think that's worth capturing in a comment.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/bloom-player-core.tsx, line 1837 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-YzmrOA4UkZg0GsVhF:-N-ZnJeI8r6r3Wna3EvM:batvodi) ([raw file](https://github.com/bloombooks/bloom-player/blob/ed820a64f15d4602ac2109c91c18d2893d23e1ee/src/bloom-player-core.tsx#L1837)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My intuition is that code that manipulates the real DOM should be in a useEffect, even if it runs on every render. This case may require it to be inline so that it runs before (e.g.) the actual render removes a div that contains one. If so, I think that's worth capturing in a comment.
</blockquote></details>

Unfortunately, bloom-player-core is still the old pre-hook paradigm. Given that, I'm not thinking of how to improve things. But it could be the brain fog...

**Review by JohnThomson — APPROVED** [review]
LGTM, but as we discussed, it may be worth investigating whether the repeated cycles of adding and removing niceScroll are a significant cost, and if so, see if we could improve it, e.g., by only doing it when current page changes, or by keeping track of the divs that have niceScroll applied and checking whether they are still in the DOM. If that doesn't look worthwhile, I think this can go as it is.

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263#-:-N-cKh_d7lpE1pu9S7lV:b-eamtuy)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/bloom-player-core.tsx, line 1837 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/263#-N-YzmrOA4UkZg0GsVhF:-N-cKK3eAecdqKWS1WPv:bwd58o2) ([raw file](https://github.com/bloombooks/bloom-player/blob/ed820a64f15d4602ac2109c91c18d2893d23e1ee/src/bloom-player-core.tsx#L1837)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately, bloom-player-core is still the old pre-hook paradigm. Given that, I'm not thinking of how to improve things. But it could be the brain fog...
</blockquote></details>

Right, you're in componentDidRender, which is exactly where you're supposed to manipulate the DOM. My bad.

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
