### PR TITLE
Play video before audio and animation (BL-9302)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/178)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/178)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/video.ts, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/178#-MQJLsGf6xbpuMKk6zXY:-MQJLsGf6xbpuMKk6zXZ:bbtf6w6) ([raw file](https://github.com/bloombooks/bloom-player/blob/5e05801021fd8aecde6db378ee60de468a41d44d/src/video.ts#L53)):*
> ```XML
>                     this.videoStartTime
>             );
>             player.playAudioAndAnimation();
> ```

Here's an idea to mull over...
Rather than passing in the core as a parameter, would it be a better architecture if the core subscribed to a video playback complete event?
Similarly for the narration side.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/178)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/178)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/video.ts, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/178#-MQJLsGf6xbpuMKk6zXY:-MQJpYlVDpws2Ze17HT-:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/5e05801021fd8aecde6db378ee60de468a41d44d/src/video.ts#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Here's an idea to mull over...
Rather than passing in the core as a parameter, would it be a better architecture if the core subscribed to a video playback complete event?
Similarly for the narration side.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/178)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/bloom-player-core.tsx, line 1673 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/178#-MQJxlvR04trhS-WGxYC:-MQJxlvR04trhS-WGxYD:b9axypu) ([raw file](https://github.com/bloombooks/bloom-player/blob/bcf17ae3540d165b3a78082c2fb119fe8e5b97da/src/bloom-player-core.tsx#L1673)):*
> ```XML
>     }
> 
>     public playAudioAndAnimation(bloomPage: HTMLElement | undefined) {
> ```

I don't see why we need to pass in bloomPage now. But if there is a good reason, go ahead and merge.

**Pull request merged**
