### PR TITLE
Stop narration when changing pages (BL-9302)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
So when I looked at this code, I felt like it was in need of a more simplified state; your first PR seemed to move us in that direction (I think? I've already forgotten). But as you take on this change, I'm back to feeling like maybe we need to just reword the state machine here? Things like ` this.pauseCurrentPlayer(); // but don't set paused state`.  Does that seem right to you?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQUOE3FBtP0M0inxG2B:blm82k9)* status: 0 of 2 files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
Sorry, let me rewrite that:

So when I looked at this code a few weeks ago, I felt like it was in need of a more simplified state; your first PR seemed to move us in that direction (I think? I've already forgotten). But as you take on this change, I'm back to feeling like maybe we need to just rework the state machine here? Things like  this:

`pauseCurrentPlayer(); // but don't set paused state`

Are what smell. Do you have the same feeling?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQUOu9S-86HddTdvGoS:b5po3ai)* status: 0 of 2 files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
This snippet was essentially a copy/paste from how video handles things.
I've renamed the method and adjusted/added some comments to try to at least clarify things.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQXsrYo04RO57-OYXSc:bsl3pdu)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
The playback state machine has been extensively reworked to make it more explicit.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQsIh5RCOLfBmPPnC2V:byjgp77)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Couple of minor suggestions, but overall it looks like a nice way to make everything clearer.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQwa5YfB7EwvxQlr530:b-r1m3ul)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/bloom-player-core.tsx, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwbIFbEb-coC5To3Py:-MQwbIFc-C186xqlcT4w:blcax4y) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L53)):*
> ```XML
>     VideoPaused, // video is paused
>     AudioPlaying, // narration, music, and/or animation are playing (or possibly finished)
>     AudioPaused // narration, music, and/or animation are paused
> ```

other possible states could be "page has nothing playable...waiting the appropriate time before auto-advancing" "video complete, and there is nothing else to play" or simply "page has no media; waiting for user to change page". Are those, like "audio finished" covered by AudioPlaying?
Seems like audio finished is somewhat different from audio playing, in that, if we are not auto-advancing, we really want to be back in state NewPageMediaPaused, so that the play/pause button changes to the Play form and can be used to restart the page's media. Likewise if video finished and there's nothing else to play. But maybe that's beyond the scope of this change?
___
*[src/bloom-player-core.tsx, line 627 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwa_Yo7dMQW8p6pIA1:-MQwa_Yo7dMQW8p6pIA2:b-fseuwh) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L627)):*
> ```XML
>             this.video.PageVideoComplete = new LiteEvent<HTMLElement>();
>             this.video.PageVideoComplete.subscribe(pageElement => {
>                 this.playAudioAndAnimation(pageElement); // allow replay from beginning of page
> ```

It's not obvious how doing this allows replay from beginning of page. Seems more like, now we've finished video, we immediately start playing audio etc. (if any)
___
*[src/bloom-player-core.tsx, line 873 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwYlhTEy3wgLDlq9js:-MQwYlhU9j2gEe2mQX_O:b-9avdsq) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L873)):*
> ```XML
>         if (BloomPlayerCore.currentPlaybackMode === PlaybackMode.VideoPlaying) {
>             this.video.pause();
>             BloomPlayerCore.currentPlaybackMode = PlaybackMode.VideoPaused;
> ```

this.video.play() sets the appropriate state itself. Is there a reason why pause() shouldn't do the same? Likewise this.narration.pause()?
___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQw_Y3s1uu0W1-pmbsp:b-la1ryb) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
> ```XML
> 
>     // This pauses the current player without setting the "AudioPaused" state.
>     // (There's no "stop" method on player, only a "pause" method.)
> ```

Maybe add something like, "This should only be used when we won't resume except by restarting (e.g., when we leave the page in mid play)". It does not set this.startPause.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/bloom-player-core.tsx, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwbIFbEb-coC5To3Py:-MQwrmM93RT0AV9jZOo9:blkltmw) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

other possible states could be "page has nothing playable...waiting the appropriate time before auto-advancing" "video complete, and there is nothing else to play" or simply "page has no media; waiting for user to change page". Are those, like "audio finished" covered by AudioPlaying?
Seems like audio finished is somewhat different from audio playing, in that, if we are not auto-advancing, we really want to be back in state NewPageMediaPaused, so that the play/pause button changes to the Play form and can be used to restart the page's media. Likewise if video finished and there's nothing else to play. But maybe that's beyond the scope of this change?
</blockquote></details>

I added a MediaFinished state.  Setting this state should enable the play button, but that's a separate issue beyond the scope of this one.
___
*[src/bloom-player-core.tsx, line 627 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwa_Yo7dMQW8p6pIA1:-MQwdmD5AaA-zbLzLc0r:b-jxlql6) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L627)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious how doing this allows replay from beginning of page. Seems more like, now we've finished video, we immediately start playing audio etc. (if any)
</blockquote></details>

I changed the comment.
___
*[src/bloom-player-core.tsx, line 873 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQwYlhTEy3wgLDlq9js:-MQwfpFA9bJs7OOPPvNY:b-vfg7td) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/bloom-player-core.tsx#L873)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

this.video.play() sets the appropriate state itself. Is there a reason why pause() shouldn't do the same? Likewise this.narration.pause()?
</blockquote></details>

I was trying to keep the state setting all inside BloomPlayerCore as much as possible.
I've moved the state setting to the video.pause() and audio.pause() methods.  The latter depends on music.pause() and animations.PauseAnimation not checking the state, which is currently true.   I added a comment to this effect in the code.
___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQweFtL3ebZJ4tV5KT1:bdcu52f) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe add something like, "This should only be used when we won't resume except by restarting (e.g., when we leave the page in mid play)". It does not set this.startPause.
</blockquote></details>

That's not quite right.  I've expanded the comment to try to make it clearer.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/bloom-player-core.tsx, line 1470 at r4](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQx3tzE5MQxUxQuQbTq:-MQx3tzE5MQxUxQuQbTr:bpuzp0s) ([raw file](https://github.com/bloombooks/bloom-player/blob/464481d16936bf2b6de7666f1c02a2654927d261/src/bloom-player-core.tsx#L1470)):*
> ```
> // TODO: at this point, signal BloomPlayerControls to switch the pause button to show play.
> ```
I think this is BL-9304? But tricky because we want to be sure to start playing again (and show pause) when changing pages).
But looks like you handled that already above.
___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQx20mo4ZA9VNzwpF2j:b-iok6rd) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
Something about this still doesn't seem right to me.
If we call this when pausing, why do we call it stopPlaying? 
Would it be more clear if we simply called `pause` with a new parameter called `allowResume` which defaults to true?

The current code allows us to pick up where we left off with narration, even if leaving the page and returning. I don't actually see anything in the code which breaks that, but it seems from your comment that we have. Do we have to?

>
    // Note that there's no "stop" method on player, only a "pause" method.  This method is
    // used both when "pausing" the narration while viewing a page and when stopping narration
    // when changing pages.

Is the case when pausing the narration going through `pause()`? If so, I think we might need to specify in this comment that, in that case, the caller **is** handling allowing resumption. The first time I read it, I thought the opposite.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182#-:-MQxLYTYCvET0oBBh2SY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQxLAzJ4_ZuCbbRd63R:bmzqa39) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Something about this still doesn't seem right to me.
If we call this when pausing, why do we call it stopPlaying? 
Would it be more clear if we simply called `pause` with a new parameter called `allowResume` which defaults to true?

The current code allows us to pick up where we left off with narration, even if leaving the page and returning. I don't actually see anything in the code which breaks that, but it seems from your comment that we have. Do we have to?

>
    // Note that there's no "stop" method on player, only a "pause" method.  This method is
    // used both when "pausing" the narration while viewing a page and when stopping narration
    // when changing pages.

Is the case when pausing the narration going through `pause()`? If so, I think we might need to specify in this comment that, in that case, the caller **is** handling allowing resumption. The first time I read it, I thought the opposite.
</blockquote></details>

There seems to be only one startPause variable, not one per page, so using it to allow resuming audio on pages other than the current one is surely unworkable without a significant enhancement?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQxVq1e9BE7HaIuhG80:bca22of) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There seems to be only one startPause variable, not one per page, so using it to allow resuming audio on pages other than the current one is surely unworkable without a significant enhancement?
</blockquote></details>

Perhaps we got the feature by accident, but this is the feature I am referring to:
Play a page. Pause before it completes. Switch pages. Switch back. Play. Playback resumes where it left off.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-core.tsx, line 1470 at r4](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQx3tzE5MQxUxQuQbTq:-MQxOjBqCj3F6_fYTfZ2:bgs0xhj) ([raw file](https://github.com/bloombooks/bloom-player/blob/464481d16936bf2b6de7666f1c02a2654927d261/src/bloom-player-core.tsx#L1470)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // TODO: at this point, signal BloomPlayerControls to switch the pause button to show play.
> ```
I think this is BL-9304? But tricky because we want to be sure to start playing again (and show pause) when changing pages).
But looks like you handled that already above.
</blockquote></details>

No, BL-9304 is a new overlay icon on top of the video as I read it.  My comment has to do with the state of the play/pause button in BloomPlayerControls.  Although maybe if the latter worked properly, BL-9304 wouldn't be needed.
___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQxRG3PA0Ry032otnA5:b-7b1qes) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Perhaps we got the feature by accident, but this is the feature I am referring to:
Play a page. Pause before it completes. Switch pages. Switch back. Play. Playback resumes where it left off.
</blockquote></details>

If you hit the pause button while audio is playing and move around one or more pages without unpausing, and return to the original page where you paused, then hitting the play button will pick up where you left off.  Hitting the play button on any other page will start at its beginning.  I think this is the feature Andrew is talking about.  It still works for audio.
If you pause the video and move around, coming back and hitting play starts the video over again from the beginning.  It's likely that going off the page sets "videoEnded" by calling onended.  This hasn't changed, so I doubt the behavior of video resuming has changed.
I renamed the method to pausePlaying(), and added a comment in hidingPage().  This puts it back in the state that JohnH didn't much like earlier, but I don't think it can really be improved.  It's exactly the same thing that happens in Video.hidingPage().

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/narration.ts, line 716 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/182#-MQw_Y3s1uu0W1-pmbso:-MQx_TdK-e8c99N-zmeL:biia5t) ([raw file](https://github.com/bloombooks/bloom-player/blob/5d380973fae5f477bef3c3d8646d9fd43a111983/src/narration.ts#L716)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If you hit the pause button while audio is playing and move around one or more pages without unpausing, and return to the original page where you paused, then hitting the play button will pick up where you left off.  Hitting the play button on any other page will start at its beginning.  I think this is the feature Andrew is talking about.  It still works for audio.
If you pause the video and move around, coming back and hitting play starts the video over again from the beginning.  It's likely that going off the page sets "videoEnded" by calling onended.  This hasn't changed, so I doubt the behavior of video resuming has changed.
I renamed the method to pausePlaying(), and added a comment in hidingPage().  This puts it back in the state that JohnH didn't much like earlier, but I don't think it can really be improved.  It's exactly the same thing that happens in Video.hidingPage().
</blockquote></details>

As I don't have any specific ways to improve things, I'm approving.

**Pull request merged**
