### PR TITLE
Modernize build, storybook, crowdin

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332)* status: 0 of 43 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[`index-for-developing.html` line 13 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qM3me21R92Hv8h-y3:-O9qM3me21R92Hv8h-y4:b-apfckp) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/index-for-developing.html#L13)):*
> ```HTML
> <body>
>     <iframe id="player-iframe"
>         failssrc="bloomplayer-for-developing.htm?url=testBooks/Bloom5.4-activities/Bloom5.4-activities.htm"
> ```

Unless you have a specific reason, I'd prefer to see the one that actually does something come first.
___
*[`package.json` line 37 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qMtYB-R68y4sFG4kc:-O9qMtYB-R68y4sFG4kd:b2ibbcx) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/package.json#L37)):*
> ```JSON
>         "jquery.nicescroll": "^3.7.6",
>         "react": "^17.0.2",
>         "react-dom": "^17.0.2",
> ```

I have a vague recollection that in a library, React should be a peer dependency. Something to do with the danger of ending up with two versions of it. We probably get away with it since bloom-player is always loaded into its own iframe, so probably not a problem. Just thought I'd mention it in case you thought it worth looking into while we're rearranging everything.
___
*[`src/activities/domActivities/SimpleCheckboxQuiz.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qPUWL5rVOARfyRZDO:-O9qPUWL5rVOARfyRZDP:bqke05i) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/activities/domActivities/SimpleCheckboxQuiz.ts#L3)):*
> ```XML
> import { ActivityContext } from "../ActivityContext";
> import { IActivityObject } from "../activityManager";
> import styles from "./SimpleCheckboxQuiz.css?inline";
> ```

I'm curious why this works with vite, but doing it for BloomPlayer's main CSS didn't.
___
*[`src/activities/domActivities/SimpleDomChoice.ts` line 4 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qQJ7OC5bK9IG3YXU1:-O9qQJ7OC5bK9IG3YXU2:b-vp48p7) ([raw file](https://github.com/BloomBooks/bloom-player/blob/9ada4813a4d88d281fec2882e3df45f62c94b343/src/activities/domActivities/SimpleDomChoice.ts#L4)):*
> ```XML
> import { IActivityObject } from "../activityManager";
> // tslint:disable-next-line: no-submodule-imports
> /* Not using. See comment below:
> ```

I don't see any relevant new comment below, nor anything that would obviously replace this.
___
*[`src/activities/dragActivities/DragToDestination.ts` line 9 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qQVkl7PVIkns5r_Ia:-O9qQVkl7PVIkns5r_Ib:b-ah1e8b) ([raw file](https://github.com/BloomBooks/bloom-player/blob/9ada4813a4d88d281fec2882e3df45f62c94b343/src/activities/dragActivities/DragToDestination.ts#L9)):*
> ```XML
> } from "../../dragActivityRuntime";
> // tslint:disable-next-line: no-submodule-imports
> /* Not using. See comment below:
> ```

Again, not seeing a new comment or anything to replace this.
___
*[`src/l10n/all-messages.json` line 1 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qRsSR-828DYxBdKnq:-O9qRsSR-828DYxBdKnr:b-9tlv27) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/l10n/all-messages.json#L1)):*
> ```JSON
> {  "ar": {
> ```

This is apparently a file generated at build time. It's unusual to check in such files, but maybe CrowdIn requires it? Or is there some other reason? I'm not sure where it would make sense to document the reason, but it would be good if you could.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332)* status: 0 of 43 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`index-for-developing.html` line 13 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qM3me21R92Hv8h-y3:-O9vNiie0F-aXFquPHxW:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/index-for-developing.html#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unless you have a specific reason, I'd prefer to see the one that actually does something come first.
</blockquote></details>

Done.
___
*[`package.json` line 37 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qMtYB-R68y4sFG4kc:-O9vNsTgCRCbSx8GF1pl:btz0oic) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/package.json#L37)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have a vague recollection that in a library, React should be a peer dependency. Something to do with the danger of ending up with two versions of it. We probably get away with it since bloom-player is always loaded into its own iframe, so probably not a problem. Just thought I'd mention it in case you thought it worth looking into while we're rearranging everything.
</blockquote></details>

Your're right, but Bloom Payer is actually not used as a library. It's SPA: an HTML file with its own javascript. So it needs all its dependencies.

Once we add a library portion, it will have to do as you're saying.
___
*[`src/activities/domActivities/SimpleCheckboxQuiz.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qPUWL5rVOARfyRZDO:-O9vOYTjEHY5WN7yvMgE:behti78) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/activities/domActivities/SimpleCheckboxQuiz.ts#L3)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm curious why this works with vite, but doing it for BloomPlayer's main CSS didn't.
</blockquote></details>

Sorry I'm not following you.
___
*[`src/activities/domActivities/SimpleDomChoice.ts` line 4 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qQJ7OC5bK9IG3YXU1:-O9vOu231QXTIUYQpuJ5:bqcb732) ([raw file](https://github.com/BloomBooks/bloom-player/blob/9ada4813a4d88d281fec2882e3df45f62c94b343/src/activities/domActivities/SimpleDomChoice.ts#L4)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see any relevant new comment below, nor anything that would obviously replace this.
</blockquote></details>

This section was commented out. So that code is not used.  Time for Remarkable to bring on source code highlighting!
___
*[`src/activities/dragActivities/DragToDestination.ts` line 9 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qQVkl7PVIkns5r_Ia:-O9vP5aT24Yb-NXb7t8K:bp45n2b) ([raw file](https://github.com/BloomBooks/bloom-player/blob/9ada4813a4d88d281fec2882e3df45f62c94b343/src/activities/dragActivities/DragToDestination.ts#L9)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, not seeing a new comment or anything to replace this.
</blockquote></details>

Right, still just old commented out code.
___
*[`src/l10n/all-messages.json` line 1 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qRsSR-828DYxBdKnq:-O9vPBmr1xHIr2amPsH4:bnzqija) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/l10n/all-messages.json#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is apparently a file generated at build time. It's unusual to check in such files, but maybe CrowdIn requires it? Or is there some other reason? I'm not sure where it would make sense to document the reason, but it would be good if you could.
</blockquote></details>

It's just a convenience so that people don't get errors if they haven't run the crowdin sync or don't have permission to do so.

**Review by JohnThomson — APPROVED** [review]
Approving as a whole, hoping someone else has looked at the vite config, wondering if what you're doing with CSS in SimpleCheckBoxQuiz

> Reviewed 40 of 43 files at r1, 255 of 255 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-:-O9ye3AG1qwV3kfbTj3D:b-uh0vbx)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/activities/domActivities/SimpleCheckboxQuiz.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qPUWL5rVOARfyRZDO:-O9ybWFr7QH40vFphveh:b2aop68) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/activities/domActivities/SimpleCheckboxQuiz.ts#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry I'm not following you.
</blockquote></details>

You modified index.htm to pull in a css file with a sha because, as I understood the comments, importing styles like this so they become part of the compiled JS doesn't work in vite. So I'm wondering why you can do it here but not there. Is this file built some other way? Maybe it's because this is just pulling in raw CSS whereas the other is compiled from less?
But I assume you've tried it and it DOES work, so things needn't be held up over this. OTOH if we can simplify handling the main CSS file that sounds like a good thing.
But I guess I'm totally misunderstanding, because bloom-player-core.ts still imports all kinds of css and less files, and now I can't even find the comment that said something about how bloomPlayer.css can't be imported because of a bug in vite.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/activities/domActivities/SimpleCheckboxQuiz.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-O9qPUWL5rVOARfyRZDO:-OAIR3ujEfOULe6YCRnB:b232eo3) ([raw file](https://github.com/BloomBooks/bloom-player/blob/bf9df839c4add89a2de70f1af0f458a60aa1da3a/src/activities/domActivities/SimpleCheckboxQuiz.ts#L3)):*
> importing styles like this so they become part of the compiled JS doesn't work in vite

You can import them. They become part of the bloomPlayer.css.  Think of it as a one of the bundles. If we wanted it all in js, we could try `vite-plugin-css-injected-by-js`.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Review by JohnThomson — APPROVED** [review]
LGTM. Still hoping someone familiar with vite can review those parts. Also not sure whether we decided this is a good time to risk such a major change, though I'm not sure when would be better.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/332#-:-OAIWFHo7B27ejKks8DB:b-gyzkza)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
