### PR TITLE
Support data-sound and prevent video click toggling app bar

### PR DESCRIPTION
**Pull request by JohnThomson**
This also brings dragActivityRuntime.ts up to date with Bloom Desktop.
The only change to that file, I believe, that hasn't already been reviewed there is making playSoundOf exported and adding preventDefault/stopPropagation. (Also the only change we actually need here until bloom games go live, but I prefer to keep the files in sync.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/321)

### CODE REVIEW

**Review by StephenMcConnel — COMMENTED** [review]
Looks okay as far as I can see, but another reviewer wouldn't hurt.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/321#-:-O75ZAP3AEJ_0U5c9toT:bm9ie46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/321)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks fine, but with semantic-release, a release won't be created unless the commit message conforms to the proper format.
So, the first commit should be prepended with "feat: " and the second with "fix: "

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/321#-:-O764Led2CmLeffyy-V8:bqen9xx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/321)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
