### PR TITLE
feat: Make images and text follow data-href when touched (BL-13879)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/bloom-player-core.tsx` line 345 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-O7iw3oSDk57B3p16z0K:-O7iw3oSDk57B3p16z0L:bn16l6t) ([raw file](https://github.com/BloomBooks/bloom-player/blob/7dac1d17d66d64eb8e54f4fa09a4cbce6d5d36bc/src/bloom-player-core.tsx#L345)):*
> ```XML
>     handleDocumentLevelClick(e: any) {
>         const targetElement = e.target as HTMLElement;
>         if (targetElement && targetElement.attributes["data-href"]) {
> ```

This will only work if the data-href is right on the target element (the lowest-level thing that got clicked). For example, to make one work for a text bubble, we would have to put it on every paragraph and every span in every bloom-editable. 
I'd suggest that instead we do something like 
const targetElement = (e.target as HTMLElement).closest("[data-href]") as HTMLElement
which will allow us to put it on a translation group, an overlay, an image container, or even on the whole page.
___
*[`src/bloom-player-core.tsx` line 369 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-O7iy1Ri-XRbIxxlTpkP:-O7iy1Ri-XRbIxxlTpkQ:b-81zycq) ([raw file](https://github.com/BloomBooks/bloom-player/blob/7dac1d17d66d64eb8e54f4fa09a4cbce6d5d36bc/src/bloom-player-core.tsx#L369)):*
> ```XML
>                     // (Maybe we should send a message to the host instead?  or can the
>                     // host intercept this and open a browser to handle it?)
>                     window.open(href, "_blank", "noreferrer");
> ```

phone apps can certainly intercept. I hope you at least tested that this works if BP is running in a browser (e.g., storybook)?

**Review by JohnThomson — COMMENTED** [review]
Could we put a trivial example...maybe a link to Blorg...in one of the local test books used for storybook, to make it easier to test at least the https: option? We may well already have a book that tests page links.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-:-O7izhRz-aGbAgpHm2Cw:b-ssjspa)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/bloom-player-core.tsx` line 345 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-O7iw3oSDk57B3p16z0K:-O7jQO-M07QIDh0TQLxu:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-player/blob/7dac1d17d66d64eb8e54f4fa09a4cbce6d5d36bc/src/bloom-player-core.tsx#L345)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This will only work if the data-href is right on the target element (the lowest-level thing that got clicked). For example, to make one work for a text bubble, we would have to put it on every paragraph and every span in every bloom-editable. 
I'd suggest that instead we do something like 
const targetElement = (e.target as HTMLElement).closest("[data-href]") as HTMLElement
which will allow us to put it on a translation group, an overlay, an image container, or even on the whole page.
</blockquote></details>

Done.
___
*[`src/bloom-player-core.tsx` line 369 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-O7iy1Ri-XRbIxxlTpkP:-O7jQQVf5n40lBM9Wsnv:b-pipb2b) ([raw file](https://github.com/BloomBooks/bloom-player/blob/7dac1d17d66d64eb8e54f4fa09a4cbce6d5d36bc/src/bloom-player-core.tsx#L369)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

phone apps can certainly intercept. I hope you at least tested that this works if BP is running in a browser (e.g., storybook)?
</blockquote></details>

If bloom-player is running in a browser, it opens a new tab in the browser.  (I usually use yarn start, with a book illustrating what I'm working on copied to an accessible place.)  I've edited one of the storybook books to add a few data-href attributes of varying target types.

**Review by StephenMcConnel — COMMENTED** [review]
The title on the the cover page of "Testing Away Again" links to blorg.  The picture on the cover page links to page 3 of the book (which is actually the second content page).  The English paragraph on page one links to the cover page.  The French paragraph tries to link to the cover page of one of the other books in the testBooks folder.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327#-:-O7jfks85QL-j4buJKfq:bo3t44s)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
