### PR TITLE
Make BP more accessible, especially for vision-impaired (BL-9075)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/bloom-player-controls.tsx, line 424 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDHDVK5JkbvWT04Qhw:-MJDHDVK5JkbvWT04Qhx:b-wnll98) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/bloom-player-controls.tsx#L424)):*
> ```XML
>             }
>         };
>         root.addEventListener("keydown", listenForKeydown, { capture: true });
> ```

Isn't this going to add an additional listener on every render?
I'm surprised this isn't generating warnings for not including dependencies. If there are warnings, we should deal with those, even it means explicitly ignoring them if we should.
___
*[src/l10n/i18n.json, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDKRmoDCp0oMjUQEwX:-MJDKRmoDCp0oMjUQEwY:bewffa8) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/l10n/i18n.json#L44)):*
> ```JSON
>     "Button.Prev": {
>         "en": "Previous Page"
>     }
> ```

We should probably discuss these IDs. 
I can't remember for sure. But I think our current strategy is to just include these strings in Bloom.xlf (maybe we need to rethink). So we may want these IDs to match Bloom if the same strings exist there.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 424 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDHDVK5JkbvWT04Qhw:-MJDvU0bDHSujb_vH_fV:b6plciw) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/bloom-player-controls.tsx#L424)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this going to add an additional listener on every render?
I'm surprised this isn't generating warnings for not including dependencies. If there are warnings, we should deal with those, even it means explicitly ignoring them if we should.
</blockquote></details>

It's always the same function instance, so addEventListener won't add it more than once. See the comment above.
There are no dependencies listed, not even an empty list, so this effect runs on every render, which produces no warnings. Maybe that's not necessary but it doesn't cost much.
___
*[src/l10n/i18n.json, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDKRmoDCp0oMjUQEwX:-MJDwSQD4vHNZnZ5Rwvj:b32w0x) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/l10n/i18n.json#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We should probably discuss these IDs. 
I can't remember for sure. But I think our current strategy is to just include these strings in Bloom.xlf (maybe we need to rethink). So we may want these IDs to match Bloom if the same strings exist there.
</blockquote></details>

OK

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/l10n/i18n.json, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDKRmoDCp0oMjUQEwX:-MJDzmkSEiVUTyvOkFff:bwqc0yo) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/l10n/i18n.json#L44)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK
</blockquote></details>

As far as I can find, only a very few have close equivalents. The nearest are problably Common.Next (comment talks about next page in a wizard) and Common.BackButton which is for going back a page in a wizard. Since I wanted to say "Next Page" and "Previous Page" neither is very appealing to reuse.
But maybe we should prepend BloomPlayer to all of them?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 424 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDHDVK5JkbvWT04Qhw:-MJE7sH73cy3z9BcgHPP:bsv9wav) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/bloom-player-controls.tsx#L424)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's always the same function instance, so addEventListener won't add it more than once. See the comment above.
There are no dependencies listed, not even an empty list, so this effect runs on every render, which produces no warnings. Maybe that's not necessary but it doesn't cost much.
</blockquote></details>

Sorry; I missed reading that comment somehow.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/158)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/l10n/i18n.json, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/158#-MJDKRmoDCp0oMjUQEwX:-MJEJtOy8W27dJWHzq3S:b64621u) ([raw file](https://github.com/bloombooks/bloom-player/blob/fb1d40c2cff1b3bd0b233a6174f75312b54063d1/src/l10n/i18n.json#L44)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As far as I can find, only a very few have close equivalents. The nearest are problably Common.Next (comment talks about next page in a wizard) and Common.BackButton which is for going back a page in a wizard. Since I wanted to say "Next Page" and "Previous Page" neither is very appealing to reuse.
But maybe we should prepend BloomPlayer to all of them?
</blockquote></details>

We decided to push off i18n improvements to a further change.

**Pull request merged**
