### PR TITLE
BL-8993 Toggle reading image descriptions

### PR DESCRIPTION
**Pull request by gmartin7**
* icon button disappears if no image descriptions
* icon button switches between on and off
* if button clicked while on a page, that page is re-read
   with the new settings (even if mid-sentence)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/bloom-player-controls.tsx, line 504 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrdeOJ4YJK1RhZCrwl:-MVrdeOJ4YJK1RhZCrwm:b-u9u12i) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L504)):*
> ```
> bookHasImageDescriptions
> ```
Seems like this fits better in reportPageProperties. What do you think?
___
*[src/bloom-player-controls.tsx, line 671 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrjySU89G6ef_NDzKc:-MVrjySU89G6ef_NDzKd:b-cs0n5l) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L671)):*
> ```
> bookHasImageDescriptions && readImageDescriptions
> ```
Feels like it would be cleaner to let the core provide the piece of this logic stating if there are image descriptions or not.
For one thing, there could be a theoretical use of the core without the control.

If it helps, the prop could be shouldReadImageDescriptions or readImageDescriptionsIfPresent, but I'm not sure that's necessary.
___
*[src/bloom-player-core.tsx, line 232 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrj-FpDDzTIoYEb4x1:-MVrj-FpDDzTIoYEb4x2:b-6l5pbg) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-core.tsx#L232)):*
> ```XML
>     // This is true iff we have image descriptions in the book (somewhere)
>     // and the icon in the controls is active.
>     public static readImageDescriptions: boolean;
> ```

Why do we need this static? Why can't we use the prop everywhere?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/bloom-player-controls.tsx, line 504 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrdeOJ4YJK1RhZCrwl:-MVrp5kG4BBjDle18MTw:b-ln1ai7) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L504)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> bookHasImageDescriptions
> ```
Seems like this fits better in reportPageProperties. What do you think?
</blockquote></details>

I don't think so. I want the icon to appear on a per book basis, not a per page basis. If the entire book doesn't have image descriptions, we don't show the icon at all. If this particular page doesn't have them, but the rest of the book does, I think the user should still be able to interact with the icon.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 671 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrjySU89G6ef_NDzKc:-MVrtRHk3CewkHBavaGP:bht5vk2) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L671)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> bookHasImageDescriptions && readImageDescriptions
> ```
Feels like it would be cleaner to let the core provide the piece of this logic stating if there are image descriptions or not.
For one thing, there could be a theoretical use of the core without the control.

If it helps, the prop could be shouldReadImageDescriptions or readImageDescriptionsIfPresent, but I'm not sure that's necessary.
</blockquote></details>

I think that's better. Not sure, what do you think?
___
*[src/bloom-player-core.tsx, line 232 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrj-FpDDzTIoYEb4x1:-MVrpzB1A2BdQSt1XRzo:bbm6cao) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-core.tsx#L232)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why do we need this static? Why can't we use the prop everywhere?
</blockquote></details>

This is for use in `narration.ts`. I've added comment. See more extensive use of `currentPlaybackMode` above.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/bloom-player-controls.tsx, line 504 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrdeOJ4YJK1RhZCrwl:-MVrzdGm3TYWZoE5M3my:b-18ita1) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L504)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I don't think so. I want the icon to appear on a per book basis, not a per page basis. If the entire book doesn't have image descriptions, we don't show the icon at all. If this particular page doesn't have them, but the rest of the book does, I think the user should still be able to interact with the icon.
</blockquote></details>

Yeah, I missed it was a the page level somehow.
___
*[src/bloom-player-controls.tsx, line 671 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrjySU89G6ef_NDzKc:-MVrzkWw2P-BQd6W3ABf:b-izbj8h) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-controls.tsx#L671)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I think that's better. Not sure, what do you think?
</blockquote></details>

Yes, thanks
___
*[src/bloom-player-controls.tsx, line 731 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVs08cVEBidCqJ7wqjZ:-MVs08cVEBidCqJ7wqj_:b-thkury) ([raw file](https://github.com/bloombooks/bloom-player/blob/892785d1ee2710fe7bf0a5149c0b0f453ff9cd0d/src/bloom-player-controls.tsx#L731)):*
> ```XML
>                     "readImageDescriptions",
>                     true
>                 )}
> ```

As I stated in the other PR, I'm not sure this is useful at this point. I think you can just initialize the state to true and drop the prop.
___
*[src/bloom-player-core.tsx, line 232 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrj-FpDDzTIoYEb4x1:-MVryKOr-y985EU_Ph4M:b-97qjnh) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-core.tsx#L232)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This is for use in `narration.ts`. I've added comment. See more extensive use of `currentPlaybackMode` above.
</blockquote></details>

Still doesn't seem right. 
I wasn't in love with currentPlaybackMode, either, if I recall. But somehow we decided it was needed. That, at least, is used in multiple files and even needs to be set in multiple places.

Would it work to have a set method in narration?
`narration.setReadImageDescriptions(props.shouldReadImageDescriptions)` or `narration.includeImageDescriptions(props.shouldReadImageDescriptions)` or similar?
___
*[src/bloom-player-core.tsx, line 228 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrzs4PB7FJTAZ-pcyl:-MVrzs4PB7FJTAZ-pcym:bd9sdwq) ([raw file](https://github.com/bloombooks/bloom-player/blob/892785d1ee2710fe7bf0a5149c0b0f453ff9cd0d/src/bloom-player-core.tsx#L228)):*
> ```
> // Used in narration.ts.
> ```
Not just there. Can probably just remove this unless you want to fully expand it to make it complete (which would be more about what it means and how it is used).

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 731 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVs08cVEBidCqJ7wqjZ:-MVwOMWg5AJU0JjpP9T9:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/892785d1ee2710fe7bf0a5149c0b0f453ff9cd0d/src/bloom-player-controls.tsx#L731)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As I stated in the other PR, I'm not sure this is useful at this point. I think you can just initialize the state to true and drop the prop.
</blockquote></details>

Done.
___
*[src/bloom-player-core.tsx, line 232 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrj-FpDDzTIoYEb4x1:-MVwpCms8trFc-3SLQz9:b-uy6u3o) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-core.tsx#L232)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Still doesn't seem right. 
I wasn't in love with currentPlaybackMode, either, if I recall. But somehow we decided it was needed. That, at least, is used in multiple files and even needs to be set in multiple places.

Would it work to have a set method in narration?
`narration.setReadImageDescriptions(props.shouldReadImageDescriptions)` or `narration.includeImageDescriptions(props.shouldReadImageDescriptions)` or similar?
</blockquote></details>

I used a typescript property. Is that good, or too complicated? Seems good to me.
___
*[src/bloom-player-core.tsx, line 228 at r2](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrzs4PB7FJTAZ-pcyl:-MVwOgwcBl9ysdkJ-kUe:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/892785d1ee2710fe7bf0a5149c0b0f453ff9cd0d/src/bloom-player-core.tsx#L228)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // Used in narration.ts.
> ```
Not just there. Can probably just remove this unless you want to fully expand it to make it complete (which would be more about what it means and how it is used).
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/bloom-player-core.tsx, line 232 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVrj-FpDDzTIoYEb4x1:-MVwySdA5Fm5OwgXiczQ:bpx2jky) ([raw file](https://github.com/bloombooks/bloom-player/blob/4d266ed5af7f45725585139f906bad2084a0564e/src/bloom-player-core.tsx#L232)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I used a typescript property. Is that good, or too complicated? Seems good to me.
</blockquote></details>

Moved comment thread to that location...
___
*[src/narration.ts, line 623 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVwyYYO5XPeK68IjMop:-MVwyYYO5XPeK68IjMoq:b80qs8i) ([raw file](https://github.com/bloombooks/bloom-player/blob/3436939a8fded2ad97d0f7b6ff82737f81657433/src/narration.ts#L623)):*
> ```XML
>     public set includeImageDescriptions(includeImageDescriptions: boolean) {
>         this._includeImgDesc = includeImageDescriptions;
>     }
> ```

This seems more complicated than
```
    private includeImageDescriptions: boolean = true;
    public setIncludeImageDescriptions(includeImageDescriptions: boolean) {
        this.includeImageDescriptions= includeImageDescriptions;
    }
```
but maybe this has some benefit I don't know about?

And, so far, we haven't used underscore for member variables in this project, so let's drop that. And you might as well move it up to where the other private member variables are.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/narration.ts, line 623 at r3](https://reviewable.io/reviews/bloombooks/bloom-player/197#-MVwyYYO5XPeK68IjMop:-MVwzi1q5sdkYrM33vZH:bn4to3j) ([raw file](https://github.com/bloombooks/bloom-player/blob/3436939a8fded2ad97d0f7b6ff82737f81657433/src/narration.ts#L623)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This seems more complicated than
```
    private includeImageDescriptions: boolean = true;
    public setIncludeImageDescriptions(includeImageDescriptions: boolean) {
        this.includeImageDescriptions= includeImageDescriptions;
    }
```
but maybe this has some benefit I don't know about?

And, so far, we haven't used underscore for member variables in this project, so let's drop that. And you might as well move it up to where the other private member variables are.

</blockquote></details>

Done. I just thought it was more of a property sort of thing than a variable to set, but I went with what you had.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
