### PR TITLE
Support adjusting comic bubbles by language (BL-10391)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/bloom-player-core.tsx` line 1282 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3BHajEhQYmCFYB8UX:-NP3BHajEhQYmCFYB8UY:bl80nij) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L1282)):*
> ```XML
>                     altSvg.classList.remove("comical-alternate");
>                     altSvg.classList.add("comical-generated");
>                     altSvg.removeAttribute("style");
> ```

I'm not excited about removing the style attribute altogether.
What if someone has custom css?
Or what if we introduce another style? We would suddenly have backward compatibility issues.
Am I thinking clearly? It should be fairly simple to set the attribute value to the previous value with `.replace('display: none')` I think.
___
*[`src/bloom-player-core.tsx` line 2912 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3C0eI7cTxtLAoUEgU:-NP3C0eI7cTxtLAoUEgV:bg4xuts) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L2912)):*
> ```XML
>     style: string;
>     tails: object[];
> }
> ```

If I'm reading the code correctly, we actually only use style currently. But maybe it isn't worth making that explicit.

**Comment by andrew-polk** [comment]
*[`src/bloom-player-core.tsx` line 1282 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3BHajEhQYmCFYB8UX:-NP3Eb9Q87gsr4x_bYjP:b-3qh8c1) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L1282)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about removing the style attribute altogether.
What if someone has custom css?
Or what if we introduce another style? We would suddenly have backward compatibility issues.
Am I thinking clearly? It should be fairly simple to set the attribute value to the previous value with `.replace('display: none')` I think.
</blockquote></details>

And for the same reason, should we always add it with the semicolon?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/bloom-player-core.tsx` line 1282 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3BHajEhQYmCFYB8UX:-NP3Xkon6VeXvEXrBUpm:b-xn3b3e) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L1282)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

And for the same reason, should we always add it with the semicolon?
</blockquote></details>

I guess the custom css doesn't come into play with the style attribute, so ignore that part.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/bloom-player-core.tsx` line 1282 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3BHajEhQYmCFYB8UX:-NPOq5zt2L8uphCPF9iQ:b-1im57e) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L1282)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess the custom css doesn't come into play with the style attribute, so ignore that part.
</blockquote></details>

I fixed it to only mess with display:
___
*[`src/bloom-player-core.tsx` line 2912 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3C0eI7cTxtLAoUEgU:-NPOZxXoBuMpdxpBGf_a:behumzd) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L2912)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm reading the code correctly, we actually only use style currently. But maybe it isn't worth making that explicit.
</blockquote></details>

I removed lang, which isn't used anywhere. The comment actually does make explicit that we don't use tails.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/bloom-player-core.tsx` line 1282 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3BHajEhQYmCFYB8UX:-NPOxY0V2cMA24JzALmi:bep0t3z) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L1282)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I fixed it to only mess with display:
</blockquote></details>

Cool. I don't think I knew you could do that. Elegant.
___
*[`src/bloom-player-core.tsx` line 2912 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/299#-NP3C0eI7cTxtLAoUEgU:-NPOxQMt6yBOkQHIDhfF:b-3rrx03) ([raw file](https://github.com/BloomBooks/bloom-player/blob/f5168ffdee7045cfd149f635bb42e7427879adb5/src/bloom-player-core.tsx#L2912)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I removed lang, which isn't used anywhere. The comment actually does make explicit that we don't use tails.
</blockquote></details>

I see it got removed from Bloom but looks like that part didn't get committed here.
At that point, LGTM

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
