### PR TITLE
Fix bug where pause/play causes highlighting to stop working (BL-8906)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/147)

### CODE REVIEW

**Comment by sujeffreyl** [comment]
___
*[src/narration.ts, line 629 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/147#-MGDzzVUEuwBwk29doIM:-MGE3kI04Zygj068ZwbO:bdcohvr) ([raw file](https://github.com/bloombooks/bloom-player/blob/051d160d288512aeb12306cd171e1958e8f202cc/src/narration.ts#L629)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Doesn't seem to be a new problem, but let's say the sound is 5s long and they already played 2s. Did we already report that 2s when they paused? If not, and if audioPlayCurrentStartTime is used to figure out the duration to report, we'll only report 3s of duration when the rest of the sound finishes.
</blockquote></details>

Yes, existing behavior is that we report 2s when they hit pause, and 3 s when it finishes. That's what I read from the code and also confirmed experimentally.

When I made this change, I just assumed the existing behavior was the desired behavior, just wrote it so as to preserve the existing behavior.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/147)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/147)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/narration.ts, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/147#-MGE0xXS86cBoHPz7FQM:-MGG29KwB7pGI7LiOb8E:b-du2e6y) ([raw file](https://github.com/bloombooks/bloom-player/blob/051d160d288512aeb12306cd171e1958e8f202cc/src/narration.ts#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Would this allow for the best of both? 
Call it something like currentlyPlayingAudioSession{Id} and make it a guid?
That's less efficient, though...
Otherwise, maybe most of the problem can be alleviated with a new name, perhaps something like currentlyPlayingAudioSession?
</blockquote></details>

I don't object to using the time as the value, just to a name that suggests that what time it is matters. I take Jeffrey's point that 'id' is getting overloaded...in fact it has a similar chance of confusion to time because it suggests that it is the element ID of the thing being played. Sorry, my bad. currentAudioSessionMarker? currentPlaybackMarker? playbackSessionIndicator? {current}audioPlaySequence?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/147)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/147)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/narration.ts, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/147#-MGE0xXS86cBoHPz7FQM:-MGJk5pPEs_OLWQXaCPC:b5a911e) ([raw file](https://github.com/bloombooks/bloom-player/blob/051d160d288512aeb12306cd171e1958e8f202cc/src/narration.ts#L45)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't object to using the time as the value, just to a name that suggests that what time it is matters. I take Jeffrey's point that 'id' is getting overloaded...in fact it has a similar chance of confusion to time because it suggests that it is the element ID of the thing being played. Sorry, my bad. currentAudioSessionMarker? currentPlaybackMarker? playbackSessionIndicator? {current}audioPlaySequence?
</blockquote></details>

how about currentAudioSessionNum?  I can get behind the idea of a session number.

**Pull request merged**
