### PR TITLE
BL-9871 Enable widgets to control navigation

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/bloom-player-controls.tsx, line 119 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-MctpIx86sR0xYuu4EC0:-MctpIx86sR0xYuu4EC1:bjhjufp) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L119)):*
> ```
>         } else if (data.name) {
>             handleActivityMessage(data.name as string);
>         }
> ```
I think this would be more robust and general (nothing about the logic ties it to activities) as something like

if message is control message (and name exists, probably)
  handleControlMessage

And change the other things in this file to strip `activity` from names.

I'm not excited about `name`. How about something like `command` or `controlAction`?
___
*[src/bloom-player-controls.tsx, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mctq2ra95Ru1UFrttWW:-Mctq2ra95Ru1UFrttWX:bdedjpv) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L202)):*
> ```
> activityHidNextPrevButtons
> ```
isHideNextPrevButtons
___
*[src/bloom-player-controls.tsx, line 653 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mcu-35Z4CEuS39EsgyK:-Mcu-35Z4CEuS39EsgyL:bdwpt46) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L653)):*
> ```
> LegacyRef
> ```
Definitely makes it seem like there should be a better way. 
But I investigated for a while and didn't find it.
Is this simply because Core is still a class (not a function component)?
Maybe deserves a comment as to why we have to do it this way?
___
*[src/activities/ActivityContext.ts, line 152 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-MctnoOu2OLc6tYBodX8:-MctnoOu2OLc6tYBodX9:b-ganx8k) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/activities/ActivityContext.ts#L152)):*
> ```XML
>     }
> 
>     public sendHideButtonsMessage() {
> ```

I think it is worth being explicit here. And also, I'm not sure it is helpful to use `send` or `message` from the users' perspective.
What do you think of

`hidePageNavigationButtons`
`navigateToNextPage`
`navigateToPreviousPage`
?

(I think we use next/previous for the button tooltips. You can verify.)
___
*[src/stories/index.tsx, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mctmt6R44KjuFJboFHc:-Mctmt6R44KjuFJboFHd:bbkdwsa) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/stories/index.tsx#L208)):*
> ```
> src/activities/test-widget-message-activity/index.htm
> ```
This wants to live in /testBooks.

(so do some other samples we have under `src`. I'm not asking you to move them, but you could.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/bloom-player-controls.tsx, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mctq2ra95Ru1UFrttWW:-Mcu1MbdDq_I-UwKKEX4:bqa3ymb) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L202)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> activityHidNextPrevButtons
> ```
isHideNextPrevButtons
</blockquote></details>

I understand the "is" from the point of view of this being a boolean...
but... the "Hid" in `activityHidNextPrevButtons` was not a misspelling.
How about nextPrevButtonsAreHidden?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/bloom-player-controls.tsx, line 653 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mcu-35Z4CEuS39EsgyK:-Mcu1uSQ9xaHCPw7flxT:b-cd635v) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L653)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> LegacyRef
> ```
Definitely makes it seem like there should be a better way. 
But I investigated for a while and didn't find it.
Is this simply because Core is still a class (not a function component)?
Maybe deserves a comment as to why we have to do it this way?
</blockquote></details>

It seems that the ref attribute has type `React.LegacyRef<BloomPlayerCore> | undefined` whereas the useRef hook provides a `React.MutableRefObject<BloomPlayerCore | undefined>`, with where the `undefined` shows up being the main problem.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/bloom-player-controls.tsx, line 653 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mcu-35Z4CEuS39EsgyK:-Mcu3CrZ4jEuEjDYlbde:b-610ivu) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L653)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

It seems that the ref attribute has type `React.LegacyRef<BloomPlayerCore> | undefined` whereas the useRef hook provides a `React.MutableRefObject<BloomPlayerCore | undefined>`, with where the `undefined` shows up being the main problem.
</blockquote></details>

Yes, I think it may well have to do with the fact that bloom-player-controls is a functional component, while the Core is a class.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: 2 of 114 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 119 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-MctpIx86sR0xYuu4EC0:-Mcu75QN7E7phyhiHOl5:bb9gikv) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L119)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>         } else if (data.name) {
>             handleActivityMessage(data.name as string);
>         }
> ```
I think this would be more robust and general (nothing about the logic ties it to activities) as something like

if message is control message (and name exists, probably)
  handleControlMessage

And change the other things in this file to strip `activity` from names.

I'm not excited about `name`. How about something like `command` or `controlAction`?
</blockquote></details>

Done. Used `controlAction`. Getting into this message means `messageType` is "control" already. Added a comment to that effect.
___
*[src/bloom-player-controls.tsx, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mctq2ra95Ru1UFrttWW:-Mcu7Hp4-ZTJAgJJcB4G:bi3007t) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/bloom-player-controls.tsx#L202)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I understand the "is" from the point of view of this being a boolean...
but... the "Hid" in `activityHidNextPrevButtons` was not a misspelling.
How about nextPrevButtonsAreHidden?
</blockquote></details>

Trying out `areNextPrevButtonsHidden`.
___
*[src/activities/ActivityContext.ts, line 152 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-MctnoOu2OLc6tYBodX8:-Mcu7whm1wFHJbcl5uYC:b-qvecql) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/activities/ActivityContext.ts#L152)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it is worth being explicit here. And also, I'm not sure it is helpful to use `send` or `message` from the users' perspective.
What do you think of

`hidePageNavigationButtons`
`navigateToNextPage`
`navigateToPreviousPage`
?

(I think we use next/previous for the button tooltips. You can verify.)

</blockquote></details>

Verified that the tooltips are Next Page/Previous Page.
Good point about these api names being user-facing. I liked your names.
___
*[src/stories/index.tsx, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/219#-Mctmt6R44KjuFJboFHc:-McuKit6E0nU9xD2WSia:bk0gcmz) ([raw file](https://github.com/bloombooks/bloom-player/blob/7d58b1d1ba16ce11d71170453cd57689b48f22c7/src/stories/index.tsx#L208)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> src/activities/test-widget-message-activity/index.htm
> ```
This wants to live in /testBooks.

(so do some other samples we have under `src`. I'm not asking you to move them, but you could.
</blockquote></details>

Done. Moved this book and 4 others.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 112 of 112 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
