### PR TITLE
Make our own video controls (BL-13957)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/329)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Found a couple of bugs, so not ready to merge yet.

**Comment by andrew-polk** [comment]
JT has decided this is ready now. It will not include any connection between the video controls and the page-level play/pause for now.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/329)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/bloom-player-ui.less` line 481 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/329#-O8xVoVMD5OULxm1MxPm:-O8xVoVMD5OULxm1MxPn:b-pl9ve9) ([raw file](https://github.com/BloomBooks/bloom-player/blob/15270ec6a7196326ba9773f08d80f824bef76d36/src/bloom-player-ui.less#L481)):*
> ```Less
>         }
>     }
> }
> ```

There is *so* much duplication between this and the BloomDesktop side. 
But anything we did to share would be painful, so I don't know what to do about it as I'm sure you didn't either.
___
*[`src/video.ts` line 62 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/329#-O8xVeO0EX7Gfs0qvH4v:-O8xVeO0EX7Gfs0qvH4w:bbq2vn8) ([raw file](https://github.com/BloomBooks/bloom-player/blob/15270ec6a7196326ba9773f08d80f824bef76d36/src/video.ts#L62)):*
> ```XML
>             const playButton = this.wrapVideoIcon(
>                 videoElement,
>                 getPlayIcon("#ffffff"),
> ```

I liked the comment on the BloomDesktop side stating why we didn't just use the MUI icons directly. We should add something like that here.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/329)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/bloom-player-ui.less` line 481 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/329#-O8xVoVMD5OULxm1MxPm:-O9A4pF8CffQYNtGC9GM:bjbk75v) ([raw file](https://github.com/BloomBooks/bloom-player/blob/15270ec6a7196326ba9773f08d80f824bef76d36/src/bloom-player-ui.less#L481)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There is *so* much duplication between this and the BloomDesktop side. 
But anything we did to share would be painful, so I don't know what to do about it as I'm sure you didn't either.
</blockquote></details>

Moreover some of it is not exactly identical. For example, the Bloom Player play/pause code integrates with analytics, even though it doesn't for now connect to the main play/pause.
___
*[`src/video.ts` line 62 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/329#-O8xVeO0EX7Gfs0qvH4v:-O9A5TBJ0DvAril8X7Z4:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-player/blob/15270ec6a7196326ba9773f08d80f824bef76d36/src/video.ts#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I liked the comment on the BloomDesktop side stating why we didn't just use the MUI icons directly. We should add something like that here.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
