### PR TITLE
Fix TextBox mode talking books with image descriptions (BL-9750)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/202)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/202)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/bloom-player-core.tsx, line 2028 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/202#-MXYCOAe7xHG-XXn1heE:-MXYCOAf-h_AKFRT6bjn:bm302m9) ([raw file](https://github.com/bloombooks/bloom-player/blob/8a188064a17fbefea74f6df9f71023f801249207/src/bloom-player-core.tsx#L2028)):*
> ```XML
>     xpath +=
>         "*[contains(@class, 'audio-sentence') or contains(@class, 'bloom-highlightSegment')]";
>     console.log("DEBUG: body=" + body.outerHTML);
> ```

Let's omit the console.log. 
Then go ahead and merge.
Thanks.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/202)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/bloom-player-core.tsx, line 2028 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/202#-MXYCOAe7xHG-XXn1heE:-MXYEut28-1mMd97Y5n9:bkimjpi) ([raw file](https://github.com/bloombooks/bloom-player/blob/8a188064a17fbefea74f6df9f71023f801249207/src/bloom-player-core.tsx#L2028)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's omit the console.log. 
Then go ahead and merge.
Thanks.
</blockquote></details>

oops.  Done.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/202)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/bloom-player-core.tsx, line 2028 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/202#-MXYCOAe7xHG-XXn1heE:-MXYFL7u7RjZ6Zw3PCoJ:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/8a188064a17fbefea74f6df9f71023f801249207/src/bloom-player-core.tsx#L2028)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

oops.  Done.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
