### PR TITLE
BL-8993 highlight image description icon

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[src/bloom-player-core.tsx, line 132 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Py_tBLd2QGwz0KNI:-MW1Py_tBLd2QGwz0KNJ:binynyn) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/bloom-player-core.tsx#L132)):*
> ```XML
> 
>     startImageDescriptionCallback: (currentSegment) => void;
>     stopImageDescriptionCallback: () => void;
> ```

I think it would be cleaner to have one callback with a boolean. What do you think?

currentSegment is not used.
___
*[src/bloom-player-core.tsx, line 809 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1PU09E8BOMh3IOjGT:-MW1PU09E8BOMh3IOjGU:bv68ak7) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/bloom-player-core.tsx#L809)):*
> ```XML
>     private handleStoppingImageDescription = () => {
>         this.props.stopImageDescriptionCallback();
>     };
> ```

I think these can all be regular functions (not lambdas). So HandlePageNarrationComplete can go back to how it was and these can be consistent with that.
Let's settle on capitalization for these. The existing ones are capitalized but probably shouldn't be.
___
*[src/controlBar.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Jn9OE8B0FnvxymR0:-MW1Jn9PE3MXR9bQDKqZ:b-wks3af) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/controlBar.tsx#L167)):*
> ```XML
>                 }
>             />
>         </ThemeProvider>
> ```

Using a theme here seems like a bit of overkill to me.
Seems simpler to just do
`color={ props.nowReadingImageDescription ? bloomYellow : bloomRed }`
where bloomYellow and bloomRed are `const`s exported from bloomPlayerTheme.

But I played with it and it doesn't like setting `color` to a string. Does setting `fill` instead work?
___
*[src/narration.ts, line 625 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Qlqh3sOhAaUQYKpI:-MW1Qlqh3sOhAaUQYKpJ:b-6muvlt) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/narration.ts#L625)):*
> ```XML
>         if (this.StoppingImageDescription) {
>             this.StoppingImageDescription.raise();
>         }
> ```

Rather than calling StoppingImageDescription everywhere PlayCompleted is called (even when we might not have been playing an image description), would it be better for the PlayCompleted event to also call the controls callback stating image descriptions are not playing?

Then again, maybe I just have a problem with the event name... saying we are stopping image description when the thing we are stopping may or may not be an image description.

Also, if after thinking through this, we are still going to end up with two image description events, can we simplify to one event with a boolean?


So...
Maybe all we need is to have PlayCompleted event also call the image description callback in controls and to change the code above to
```
                const currentSegment = element as HTMLElement;
                if (
                    currentSegment &&
                    this.ToggleImageDescription
                ) {
                    this.ToggleImageDescription.raise(this.isImageDescriptionSegment(currentSegment));
                }

```
or similar

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/bloom-player-core.tsx, line 809 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1PU09E8BOMh3IOjGT:-MW53oZ95Zybs2e4onaU:b7r22jd) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/bloom-player-core.tsx#L809)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think these can all be regular functions (not lambdas). So HandlePageNarrationComplete can go back to how it was and these can be consistent with that.
Let's settle on capitalization for these. The existing ones are capitalized but probably shouldn't be.
</blockquote></details>

At one point I had some trouble getting a `js` error about `this` not being defined. I admit I don't know too much about closures and such and why `this` might be defined or not, but I thought making a lamda fixed that problem. I can try your method and see if it works.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-core.tsx, line 132 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Py_tBLd2QGwz0KNI:-MW5WIuKDUb18TFVSCvv:b7ok33t) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/bloom-player-core.tsx#L132)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be cleaner to have one callback with a boolean. What do you think?

currentSegment is not used.
</blockquote></details>

Done. All consolidated to:
`imageDescriptionCallback: (inImageDescription: boolean) => void;`
___
*[src/bloom-player-core.tsx, line 809 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1PU09E8BOMh3IOjGT:-MW5ai827v7FVW_q0Zo5:ba1z71o) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/bloom-player-core.tsx#L809)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

At one point I had some trouble getting a `js` error about `this` not being defined. I admit I don't know too much about closures and such and why `this` might be defined or not, but I thought making a lamda fixed that problem. I can try your method and see if it works.
</blockquote></details>

As soon as I go back to regular functions I start getting `js` errors relating to `this` being undefined in the handlers. Capitalization fixed.
___
*[src/controlBar.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Jn9OE8B0FnvxymR0:-MW5PpEg3NezqPk-rHgr:b-td7jbz) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/controlBar.tsx#L167)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Using a theme here seems like a bit of overkill to me.
Seems simpler to just do
`color={ props.nowReadingImageDescription ? bloomYellow : bloomRed }`
where bloomYellow and bloomRed are `const`s exported from bloomPlayerTheme.

But I played with it and it doesn't like setting `color` to a string. Does setting `fill` instead work?
</blockquote></details>

No. I tried setting `fill` and it didn't do anything. :(
And I tried converting the `ImageDescriptionIcon` (a Mui `SvgIcon`) to a div with an `img` tag inside, but then I have trouble with opacity and other stuff. :(
Plus (JH wouldn't like this, I know), this is how they recommend doing it on the Mui site.
I'm voting for leaving this as is.
___
*[src/narration.ts, line 625 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Qlqh3sOhAaUQYKpI:-MW5V4hJ2hvK9Wy_1Rwn:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/narration.ts#L625)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Rather than calling StoppingImageDescription everywhere PlayCompleted is called (even when we might not have been playing an image description), would it be better for the PlayCompleted event to also call the controls callback stating image descriptions are not playing?

Then again, maybe I just have a problem with the event name... saying we are stopping image description when the thing we are stopping may or may not be an image description.

Also, if after thinking through this, we are still going to end up with two image description events, can we simplify to one event with a boolean?


So...
Maybe all we need is to have PlayCompleted event also call the image description callback in controls and to change the code above to
```
                const currentSegment = element as HTMLElement;
                if (
                    currentSegment &&
                    this.ToggleImageDescription
                ) {
                    this.ToggleImageDescription.raise(this.isImageDescriptionSegment(currentSegment));
                }

```
or similar
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/controlBar.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Jn9OE8B0FnvxymR0:-MWAUOZ-5yi7Lk3_QkPP:b-qei629) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/controlBar.tsx#L167)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

No. I tried setting `fill` and it didn't do anything. :(
And I tried converting the `ImageDescriptionIcon` (a Mui `SvgIcon`) to a div with an `img` tag inside, but then I have trouble with opacity and other stuff. :(
Plus (JH wouldn't like this, I know), this is how they recommend doing it on the Mui site.
I'm voting for leaving this as is.
</blockquote></details>

Let's enhance the comment a bit to explain why we went this route.

Also, I still think it is beneficial to export the yellow as a const from bloomPlayerTheme. And in this context, we don't really care that it is a warning color, right? Rather we want it to match the highlight color?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/controlBar.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/198#-MW1Jn9OE8B0FnvxymR0:-MWQMT8H1osE8UbfjujQ:bgybdxs) ([raw file](https://github.com/bloombooks/bloom-player/blob/5a5fc414ee05f96e992056ec3934e92e4f4ffcb1/src/controlBar.tsx#L167)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's enhance the comment a bit to explain why we went this route.

Also, I still think it is beneficial to export the yellow as a const from bloomPlayerTheme. And in this context, we don't really care that it is a warning color, right? Rather we want it to match the highlight color?
</blockquote></details>

Done. As noted in the issue, the new bloomHighlight is quite a bit brighter than the bloom-warning, but it matches the audio highlighting in `BP`.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
