### PR TITLE
Another attempt at handling RTL books (BL-8063)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/bloom-player-controls.tsx` line 830 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/303#-NUgw9w49gCc_qiyvhLB:-NUgw9w49gCc_qiyvhLC:b-tayi20) ([raw file](https://github.com/BloomBooks/bloom-player/blob/272ef1f7d7e2664647de9ec23a997ac3dc86e8ad/src/bloom-player-controls.tsx#L830)):*
> ```XML
>     const theme = createTheme({
>         direction: "rtl"
>     });
> ```

Deserves a comment as to why we always apply an rtl theme.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/bloom-player-controls.tsx` line 830 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/303#-NUgw9w49gCc_qiyvhLB:-NUhEAjN8wagknyS-0Tc:b-r6b9vp) ([raw file](https://github.com/BloomBooks/bloom-player/blob/272ef1f7d7e2664647de9ec23a997ac3dc86e8ad/src/bloom-player-controls.tsx#L830)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Deserves a comment as to why we always apply an rtl theme.
</blockquote></details>

No it doesn't...it deserves to be fixed so that doesn't happen!

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/bloom-player-controls.tsx` line 830 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/303#-NUgw9w49gCc_qiyvhLB:-NUhEiqyAU0jjN8e59DP:b-5ppkq6) ([raw file](https://github.com/BloomBooks/bloom-player/blob/272ef1f7d7e2664647de9ec23a997ac3dc86e8ad/src/bloom-player-controls.tsx#L830)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No it doesn't...it deserves to be fixed so that doesn't happen!
</blockquote></details>

: )

Looks good, but I think it would be worth changing `theme` to `rtlTheme`.
While doing that, maybe a brief comment explaining why that is done via a theme rather than just an attribute?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/bloom-player-controls.tsx` line 830 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/303#-NUgw9w49gCc_qiyvhLB:-NUhG_7n1yn94V0gAK17:b-gi4k45) ([raw file](https://github.com/BloomBooks/bloom-player/blob/272ef1f7d7e2664647de9ec23a997ac3dc86e8ad/src/bloom-player-controls.tsx#L830)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

: )

Looks good, but I think it would be worth changing `theme` to `rtlTheme`.
While doing that, maybe a brief comment explaining why that is done via a theme rather than just an attribute?
</blockquote></details>

Yes, good ideas. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
