### PR TITLE
Fix two problems with non-appearance books (BL-13311)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/311)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/bloom-player-pre-appearance-system-book.less` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/311#-NxyFQLgDq12ACK-RgSX:-NxyFQLgDq12ACK-RgSY:bxqwuub) ([raw file](https://github.com/BloomBooks/bloom-player/blob/32be4fcf839cee9001331229f465f17fd9e249ff/src/bloom-player-pre-appearance-system-book.less#L17)):*
> ```Less
>     !important so the only way to beat it is to be !important too. We also need more than
>     two classes. */
>     .bloomPlayer & div.bloom-page {
> ```

I don't recognize this notation. What does & in the middle of a selector mean?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/bloom-player-pre-appearance-system-book.less` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/311#-NxyFQLgDq12ACK-RgSX:-NxyHDO-48gPfCDfXVMO:b9j5nd7) ([raw file](https://github.com/BloomBooks/bloom-player/blob/32be4fcf839cee9001331229f465f17fd9e249ff/src/bloom-player-pre-appearance-system-book.less#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't recognize this notation. What does & in the middle of a selector mean?
</blockquote></details>

It just references the outer (parent) selector.
https://lesscss.org/features/#parent-selectors-feature

So, the bug I'm fixing is that I had wrapped these rules in `.bloomPlayer-page:not(.appearance-system)` but actually the rules were originally written to start with a level higher than that (`.bloomPlayer`). So I needed to properly include the `.bloomPlayer-page:not(.appearance-system)` selector in the original rules.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/bloom-player-pre-appearance-system-book.less` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-player/311#-NxyFQLgDq12ACK-RgSX:-NxyJUov9BnB-WI4Kat7:b-zcjvte) ([raw file](https://github.com/BloomBooks/bloom-player/blob/32be4fcf839cee9001331229f465f17fd9e249ff/src/bloom-player-pre-appearance-system-book.less#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It just references the outer (parent) selector.
https://lesscss.org/features/#parent-selectors-feature

So, the bug I'm fixing is that I had wrapped these rules in `.bloomPlayer-page:not(.appearance-system)` but actually the rules were originally written to start with a level higher than that (`.bloomPlayer`). So I needed to properly include the `.bloomPlayer-page:not(.appearance-system)` selector in the original rules.
</blockquote></details>

Thanks

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-player/311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
