### PR TITLE
Support Bloom Editor recording book as video (BL-10991)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/bloom-player-controls.tsx, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxanQqJ3mvWA3IXUNN2:-MxanQqJ3mvWA3IXUNN3:b-w4m6jl) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L72)):*
> ```XML
>     autoplay: autoPlayType;
>     skipActivities?: boolean;
>     videoPreviewMode?: boolean;
> ```

Some of these settings may seem obvious by their names currently, but I think we will help ourselves to document them now.
Seems like the comment for `videoSettings` should also be expanded to include specifics on what settings can be set.

As a more general question, how did you decide which settings should be part of `videoSettings` and which should be separate?
For example, image descriptions could easily be a setting separate from video.
___
*[src/bloom-player-controls.tsx, line 75 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeOFur21c65pdaUJF7:-MxeOFur21c65pdaUJF8:b-uiru5g) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L75)):*
> ```XML
>     // Send a report to Bloom API about sounds that have been played (when we reach the end
>     // of the book in autoplay).
>     reportSoundLog?: boolean;
> ```

I think this might be better as `shouldReportSoundLog`. What do you think?

However, I see that we haven't been consistent at all with boolean names above. Many of them should probably start with `is`... so maybe not worth it?

But in this case, I got into a little confusion between `reportSoundLog` (boolean param) and `reportSoundsLogged` (function).



_Code quote:_
```XML
reportSoundLog
```
___
*[src/bloom-player-controls.tsx, line 772 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxamnLb-jyo3u6jgKXM:-MxamnLb-jyo3u6jgKXN:b-yjo863) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L772)):*
> ```XML
>                 videoPreviewMode={props.videoPreviewMode}
>             />
>             {props.videoPreviewMode}
> ```

Did this get left in by accident after debugging?



_Code quote:_
```XML
{props.videoPreviewMode}
```
___
*[src/controlBar.tsx, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeRuLx3ESUKrifO6UE:-MxeRuLx3ESUKrifO6UF:b-ec3rzf) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/controlBar.tsx#L157)):*
> ```XML
>                     "Content-Type": "text/plain"
>                 }
>             }
> ```

Is there a particular reason to stringify and send as text rather than sending as json?
___
*[src/externalContext.ts, line 238 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxePh6a7IZz0ek6DXZa:-MxePh6a7IZz0ek6DXZb:b-wprkh1) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L238)):*
> ```XML
>     volume: Number;
>     startTime: string;
>     endTime?: string; // if not set, play the whole sound
> ```

Would this be better as 
`// if not set, the whole sound was played`
?



_Code quote:_
```XML
// if not set, play the whole sound
```
___
*[src/externalContext.ts, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxePve6BH4bXRDWhqx_:-MxePve6BH4bXRDWhqxa:b-d8gl0z) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L290)):*
> ```XML
>     }
>     soundsPlayed = [];
> }
> ```

It feels odd for bloom-player to have knowledge of Bloom's api.
Did you weigh the pros/cons of just using a message?
Is there ever going to be another host which would want to have the sounds info? The only thing I can think of is if we ever wanted to make the video creator a stand-alone tool. But that doesn't seem likely at the moment.
___
*[src/externalContext.ts, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeQuUp4KWSPZ8I002D:-MxeQuUp4KWSPZ8I002E:b8i157q) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L290)):*
> ```XML
>     }
>     soundsPlayed = [];
> }
> ```

As a second issue here, I would like to see more consistency with how we make calls to Bloom. Let's extract all the posts/messages to externalContext (or even a different file if we stay with posts?). Currently they are spread across three files.
Also, the call to start is conditional on the core prop. But here we call the function unconditionally and then check the param again inside the function.
___
*[src/music.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeNs3r9IzZczNGUxM_:-MxeNs3r9IzZczNGUxMa:bka33l8) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/music.ts#L180)):*
> ```XML
>         this.getPlayer().currentTime = 0;
>         this.play();
>         this.musicLogIndex = logSoundRepeat(this.musicLogIndex);
> ```

Did you consider the option of just getting the src from the player? Or if that doesn't work, even keeping track of the currently playing src? I guess you have to track the volume level, too.
If that works, I think you can get rid of the index and even `logSoundRepeat` entirely.

Later: hm, I guess you need index for paused. Still, it might be worth it to get rid of logSoundRepeat.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: 3 of 7 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxanQqJ3mvWA3IXUNN2:-Mxe_8h73xfqebCYB4I-:b-896fix) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L72)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Some of these settings may seem obvious by their names currently, but I think we will help ourselves to document them now.
Seems like the comment for `videoSettings` should also be expanded to include specifics on what settings can be set.

As a more general question, how did you decide which settings should be part of `videoSettings` and which should be separate?
For example, image descriptions could easily be a setting separate from video.
</blockquote></details>

Done.
___
*[src/bloom-player-controls.tsx, line 75 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeOFur21c65pdaUJF7:-Mxe_PSX6Wvi-nPlk4qe:bn0k8d3) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this might be better as `shouldReportSoundLog`. What do you think?

However, I see that we haven't been consistent at all with boolean names above. Many of them should probably start with `is`... so maybe not worth it?

But in this case, I got into a little confusion between `reportSoundLog` (boolean param) and `reportSoundsLogged` (function).
</blockquote></details>

I think I agree, though currently I have not also renamed the URL param. It's awkward because many of the options could be named like this (shouldAutoplay, shouldHideSwiperButtons...) but the extra length doesn't quite seem justified for most of them (to me, anyway). In the URL, however, the meaning of reportSoundLog is not ambiguous and the URL is already cumbersome enough and I think it would be more confusing and make it less consistent with the other param names.
___
*[src/bloom-player-controls.tsx, line 772 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxamnLb-jyo3u6jgKXM:-MxeazbgAhO0jDJkPgys:b-uyzobq) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L772)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did this get left in by accident after debugging?
</blockquote></details>

I think it must have.
___
*[src/controlBar.tsx, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeRuLx3ESUKrifO6UE:-MxecJphDetL9AH5U_v_:bcng87f) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/controlBar.tsx#L157)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a particular reason to stringify and send as text rather than sending as json?
</blockquote></details>

I think so and have tried to explain in a comment. John particularly wanted to make as much use as we can of the playback settings that BP already has controls for, without having to make BE aware of each of them.
___
*[src/externalContext.ts, line 238 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxePh6a7IZz0ek6DXZa:-Mxed9QH1jA5ritRFYq8:b-7um1et) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L238)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Would this be better as 
`// if not set, the whole sound was played`
?
</blockquote></details>

Kind of depends on whether your point of view is the sender or the receiver. I've tried to rewrite it to cover both.
___
*[src/externalContext.ts, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxePve6BH4bXRDWhqx_:-MxedKX-Ai_GcPH2kFRw:b-55x4bo) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L290)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It feels odd for bloom-player to have knowledge of Bloom's api.
Did you weigh the pros/cons of just using a message?
Is there ever going to be another host which would want to have the sounds info? The only thing I can think of is if we ever wanted to make the video creator a stand-alone tool. But that doesn't seem likely at the moment.
</blockquote></details>

I thought quite hard about it. I don't know of any way BE can receive messages that BP posts with postMessage. So we'd need another whole layer of wrapper (in which BP is an iframe) just to listen for the messages and pass them on to BE through the API. If we want the code in that wrapper to be typescript, it's going to end up loading the whole common bundle, and then we have to figure how to get the right URL for the player through the wrapper to the iframe...it could be done but felt like YAGNI.
Another problem is that in the case of telling Bloom when to start ffmpeg, BP needs to know that task is complete; but postMessage doesn't support waiting for a response, so we'd have to configure another message...
___
*[src/externalContext.ts, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeQuUp4KWSPZ8I002D:-MxejO7l2ka89g0t8Toi:bkxk4j6) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/externalContext.ts#L290)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As a second issue here, I would like to see more consistency with how we make calls to Bloom. Let's extract all the posts/messages to externalContext (or even a different file if we stay with posts?). Currently they are spread across three files.
Also, the call to start is conditional on the core prop. But here we call the function unconditionally and then check the param again inside the function.
</blockquote></details>

I think I've done what you're suggesting.
___
*[src/music.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeNs3r9IzZczNGUxM_:-MxekCUD-lVG9Q3rvDfM:b8l7x9t) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/music.ts#L180)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you consider the option of just getting the src from the player? Or if that doesn't work, even keeping track of the currently playing src? I guess you have to track the volume level, too.
If that works, I think you can get rid of the index and even `logSoundRepeat` entirely.

Later: hm, I guess you need index for paused. Still, it might be worth it to get rid of logSoundRepeat.
</blockquote></details>

I don't see a good way to not need the index to make pause work. Given that, I don't see a lot of advantage in getting rid of logSoundRepeat. (Though I'm starting to wonder if we should have a new SoundLog.ts. These functions don't fit well in any of the current files. What do you think?)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/music.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeNs3r9IzZczNGUxM_:-MxexRK74ZVUDUgmF_nZ:b-e00fzu) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/music.ts#L180)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see a good way to not need the index to make pause work. Given that, I don't see a lot of advantage in getting rid of logSoundRepeat. (Though I'm starting to wonder if we should have a new SoundLog.ts. These functions don't fit well in any of the current files. What do you think?)
</blockquote></details>

Yes, I think it would be worth extracting stuff to SoundLog.ts.
I would strongly consider moving the bloom api stuff there, too. On the one hand, it isn't necessarily related to sound logs in the future, but on the other hand, it currently is. And it would be nice to remove it from the more general externalContext context.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/bloom-player-controls.tsx, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxanQqJ3mvWA3IXUNN2:-Mxf9VbD0GqaR-BlCkX5:bgos95o) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed the second part of my comment (the question about settings... and should imagedesc be its own setting altogether)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/bloom-player-controls.tsx, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxanQqJ3mvWA3IXUNN2:-MxfB8YM25vXfrJ0c5sY:b-1qh4do) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/bloom-player-controls.tsx#L72)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you missed the second part of my comment (the question about settings... and should imagedesc be its own setting altogether)
</blockquote></details>

I wrote a long comment on the videoSettings which attempts to answer that. It's true that whether to play image descriptions could plausibly be a separate setting, but I'm applying yagni. Meanwhile, the things in videoSettings are the things you can control with BP control bar that are relevant to video recording playback.
___
*[src/music.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloom-player/255#-MxeNs3r9IzZczNGUxM_:-Mxfbwin1CTIgT5ia266:b-4u3nkb) ([raw file](https://github.com/bloombooks/bloom-player/blob/f466292149aa3620957ab8a42de4fce5436b6de1/src/music.ts#L180)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, I think it would be worth extracting stuff to SoundLog.ts.
I would strongly consider moving the bloom api stuff there, too. On the one hand, it isn't necessarily related to sound logs in the future, but on the other hand, it currently is. And it would be nice to remove it from the more general externalContext context.
</blockquote></details>

The messages are not all sound-related, so I called the new file videoRecordingSupport

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-player/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
